name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Install Docker
      run: docker --version | docker run postgres:latest
    